version: '3.8'
services:
  mysql:
    container_name: score_mysql
    image: mysql
    restart: always
    volumes:
      # - ./data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: score
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"

  apache-php:
    container_name: score_apache-php
    build: .
    depends_on:
      - mysql
    volumes:
      - ./www/:/var/www/html/
    ports:
      - 80:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: score_phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 100000000
    depends_on:
      - mysql
