version: '3.3'
services:
  postgres:
    image: postgres
    container_name: score_postgis
    restart: always
    environment:
      - POSTGRES_DB=maindb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d
    ports:
      - 5438:5432

  nodejs:
    image: node
    container_name: score_nodejs
    working_dir: /app/nodejs
    restart: always
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
    volumes:
      - ./nodejs:/app/nodejs
    ports:
      - 4000:3000
    command: bash -c "npm i && npm i -g nodemon && npm i -g pm2 && nodemon server.js"
